### ISSUE TITLE
Board type 1 ?

### ISSUE THREAD

**Issue by guile2912** [openLRSng/openLRSminiRX#1]
Hello Kh4,
This is a board type 1 given the LED position right ?
I am looking for a small receiver too, have you had time to build and test this design ?
Would you like any help on this ? I am not an expert, but I have designed small project on Eagle already.

Thank you very much !

**Comment by kh4** [comment]
Actually it is board type 8, I haven't had time to test it so code may be brokem.

**Comment by kh4** [comment]
closing old issues, the board is tested and works well.
