### ISSUE TITLE
Pictures of board & weight?

### ISSUE THREAD

**Issue by hialanhughes** [openLRSng/openLRSminiRX#2]
Are there any pics of this mini board so far?

**Comment by kh4** [comment]
I haven't had time to build one but I asdume I will do that during few next weeks. I will give an update then.

**Comment by hialanhughes** [comment]
Keep us posted! I'm looking forward to it!

Kind regards,
Alan - 022 156 7533

**Comment by kh4** [comment]
https://www.dropbox.com/photos/album/aeD8p6GuleMqm4w

Picture shows the one I made to test atmegas internal osc (8Mhz) and thus the resonator is not populated.

Weight is around 5g, less if headers are omitted.
