### ISSUE TITLE
Component values - missing

### ISSUE THREAD

**Issue by irun4fundotca** [openLRSng/openLRSminiRX#3]
Is there a chance you can add the values to the schematic?
they show sizes but not values to all parts

Missing values:
CAP0805   0805  C1, C2, C5, C6, C10
RESISTOR 0805  R1, R2, R3, R4, R5, R6, R7, R8

![screenshot 2015-02-25 09 49 33](https://cloud.githubusercontent.com/assets/5412981/6372666/cab657ce-bcd3-11e4-80f5-67078e260eda.png)

**Comment by kh4** [comment]
I will add tomorrow

**Comment by irun4fundotca** [comment]
I have a few parts on it :)
![p3030013](https://cloud.githubusercontent.com/assets/5412981/6486633/3baab5c0-c25a-11e4-8afc-b922dd24b36d.JPG)

**Comment by kh4** [comment]
Hmh... that is the DTFUHF (englishman) version (made with diptrace) but the
schematic is quite same, I added component values to the eagle version.
none of the values are really critical so you may substitute different
values if needed.

ke 4. maaliskuuta 2015 klo 17.36 irun4fundotca notifications@github.com
kirjoitti:
